version: "3.7"

services:
  app:
    image: node:12-alpine
    command: ["chmod", "+x", "/app/src/python/hello.py"]
    command: sh -c -u "apk update && apk add python && yarn install && yarn run dev && /app/src/python/hello.py"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
      PYTHONUNBUFFERED: 0

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data: